language: php
php:
  - 5.6
  - 7.0
  - 7.1
services:
  - mysql
  - redis-server
before_script:
  - mysql -e 'CREATE DATABASE laravelblog;'
  - cp .env.example .env
  - composer install
  - php artisan migrate
script: phpunit