dist: xenial
language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.2.5

cache:
  directories:
    - $HOME/.composer/cache

services:
  - redis-server
  - mysql

before_install:
  - phpenv config-rm xdebug.ini || true
  - printf "\n" | pecl install -f redis
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE gryengtd;'

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest;
  - travis_retry npm install -g yarn;
  - travis_retry yarn;
  - travis_retry yarn run prod;

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate --env testing
  - php artisan jwt:secret --env testing

script: php artisan test
