dist: xenial
language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.1

cache:
  directories:
    - $HOME/.composer/cache

services:
  - redis-server
  - mysql

before_install:
  - phpenv config-rm xdebug.ini || true
  - printf "\n" | pecl install -f redis
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE gryengtd;'

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest;
  - travis_retry npm install;
  - travis_retry npm run build;

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate

script: vendor/bin/phpunit
