# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ assigned ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # Runs a single command using the runners shell
      - name: Install and Build 🔧
        run: |
          npm install
          npm run prod

      # Runs a set of commands using the runners shell
      - name: Download qshell
        run: |
          wget http://devtools.qiniu.com/qshell-linux-x64-v2.4.2.zip
          unzip qshell-linux-x64-v2.4.2.zip
          chmod +x ./qshell-linux-x64-v2.4.2
          
      - name: Account to qiniu and upload
        run: |
          ./qshell-linux-x64-v2.4.2 account ${{ secrets.QINIU_AK }} ${{ secrets.QINIU_SK }} gryen-gtd
          ./qshell-linux-x64-v2.4.2 qupload2 --src-dir=/home/runner/work/gryen-gtd/gryen-gtd/public/dist --bucket=targaryen-top --key-prefix=dist/ --rescan-local=true --skip-file-prefixes=test,demo,.qrsignore --skip-path-prefixes=temp/,tmp/ --skip-fixed-strings=.svn,.git --skip-suffixes=.DS_Store,.exe

      - name: Deploy php code to alicloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALI_CLOUD_REMOTE_HOST }}
          username: ${{ secrets.ALI_CLOUD_REMOTE_USER }}
          password: ${{ secrets.ALI_CLOUD_REMOTE_PASSWORD }}
          port: ${{ secrets.ALI_CLOUD_REMOTE_PORT }}
          script: cd /home/gryen/srvs/gryen-gtd && /usr/bin/php artisan down && git fetch --all && git reset --hard origin/master && git pull && /usr/bin/composer install && /usr/bin/php artisan up
          
        
